// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../components/base/Button.vue')['default']
    Card: typeof import('./../components/card/Card.vue')['default']
    CardList: typeof import('./../components/card/CardList.vue')['default']
    Checkbox: typeof import('./../components/base/Checkbox.vue')['default']
    Icon: typeof import('./../components/base/Icon.vue')['default']
    Input: typeof import('./../components/base/Input.vue')['default']
    MainLayout: typeof import('./../components/layouts/MainLayout.vue')['default']
    NavBar: typeof import('./../components/navBar/NavBar.vue')['default']
    NavIcon: typeof import('./../components/navBar/NavIcon.vue')['default']
    NoResults: typeof import('./../components/NoResults.vue')['default']
    RangeInput: typeof import('./../components/base/RangeInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
